### ISSUE TITLE
about the encoder-decoder architecture

### ISSUE THREAD

**Issue by ShellingFord221** [Heumi/what#1]
Hi, if I don't use a network with encoder-decoder architecture, how could I get predictive mean as well as predictive variance in the function below?
![image](https://user-images.githubusercontent.com/40685673/70694163-e608eb00-1cf9-11ea-933b-b88c57258a50.png)
(i.e. how to implement 'use a single network to transform the input x, with its head split to predict both y^ as well as σ^2' without encoder-decoder architecture?)

**Comment by hmi88** [comment]
I think that dividing the last layer into two (mean, variance) is the best way. 
Paper also described the upper way.

For example,
mean = conv(last_before_layer)
variance = conv(last_before_layer)
